### PR TITLE
fix UDP handling

### PR DESCRIPTION
**Pull request by bablokb**
This PR is a fix for #58. Tested with an ESP01S and a Pico against `netcat -u -l <portnr>`:

  - `socket_connect()` saves the connection type as an object attribute and fixes at_response handling
  - `socket_send()` does not try to read a response (there is no response with UDP), this saves some ms
  - `socket_disconnect()` resets saved connection-type

### CODE REVIEW

**Comment by dhalbert** [comment]
This looks good to me. One question: did you also re-test TCP after these changes?

**Comment by bablokb** [comment]
I retested after the first commit, but not after the other two. I will do that on Monday.

**Comment by bablokb** [comment]
I retested with TCP (e.g. localtime example) and can confirm it works. 

BTW: you can find my UDP test-program here: https://github.com/bablokb/circuitpython-examples/ (subdirectory esp01-udplogger). Switching to TCP is simply done by changing `TYPE_UDP` to `TYPE_TCP` in the connect-method.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Pull request merged**
