### PR TITLE
Increased the timeout for socket_connect().

### PR DESCRIPTION
**Pull request by waiweng83**
Increased the timeout period for socket_connect() from 3 seconds to 10 seconds.
Some website especially SSL might required more than 3 seconds to be connected (eg: Telegram API).

### CODE REVIEW

**Comment by waiweng83** [comment]
Can you please help to create a release too after this is merged?
Thanks and sorry for missing out this changes in the previous pull request.

**Review by tannewt — APPROVED** [review]
Thank you! @dherrada should be able to make a release this week.

**Comment by waiweng83** [comment]
Thanks :)

**Comment by dherrada** [comment]
Releasing now

**Comment by waiweng83** [comment]
Thanks @dherrada :)

**Pull request merged**
