### PR TITLE
Fixes for "in Adafruit_CircuitPython_ESP_ATcontrol AT+CWLAP Does not return OK #48"

### PR DESCRIPTION
**Pull request by mperino**
Fixes for "in Adafruit_CircuitPython_ESP_ATcontrol AT+CWLAP Does not return OK #48".  or at least a workaround.  Buffer is defined for Challenger RP2040 WiFi Boards that keeps it from overrunning CP.

All the examples now have a if/elif for the Challenger 2040 WiFi boards, and all the examples now run!

Other small changes to add cleaner output formatting, A variable for debug level, and other small tweaks..

### CODE REVIEW

**Comment by ladyada** [comment]
whew, ok please tag when its passing CI!

will note again for the record, AT mode is really recommended by us - we always found it would fall over eventually. if it works - yay! if it doesnt...please try airlift/spi instead :)

**Comment by mperino** [comment]
Loop Fixed.. Now to repush

**Comment by mperino** [comment]
@ladyada  You are Tagged as requested (or was there a different tag to apply?)  Like #48 ?  I totally understand that airlift/SPI is the way to go (Already use it with RP2040 + Airlift.)  Using (and fixing) the AT command interface examples for Challenger 2040 Boards because I got 2 of them and AT commands is the way the board mfr recommended.  

I'm getting better (I think) at passing the CI with each contribution.. Hopefully one day soon on the first go!

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
